---
services:
  postgres:
    image: postgres:13.13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pg1234
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  kubenews:
    build:
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_DATABASE: kubenews
      DB_USERNAME: kubenews
      DB_PASSWORD: pg1234
      DB_PORT: 5432
      DB_HOST: postgres
    volumes:
      - kubenews-data:/app/data

networks:
  kubenews-net:
    driver: bridge

volumes:
  postgres-data:
  kubenews-data:
